# Site wide configuration

title: Brad Wade
subtitle: front end developer | drupal specialist | musician
description: The home for Brad Wade's web development work, portfolio, notes, documentation, and experiments.
# 120x120 px default image used for Twitter summary card
logo: bradwade-square-120.jpg
# 400x250 px default teaser image used in image archive grid
teaser: 210And2more-800-500.jpg
locale: NYC, NY
#url: http://bradwade.com

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Brad Wade
  email: brad@project47.com
  twitter: bradwade
  google:
    ad-client:
    ad-slot:
  bio: Brad Wade is a front-end web developer, Drupal specialist, and musician living in New York City.
  avatar: bradwade-bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname: project47


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
